version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Сервер будет доступен на localhost:3000
    volumes:
      - .:/app # Монтируем локальную директорию для разработки

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Фронтенд будет доступен на localhost:8080
    volumes:
      - ./frontend:/app # Монтируем директорию фронтенда
      - /app/node_modules # Сохраняем node_modules в контейнере
    depends_on:
      - server # Фронтенд стартует после сервера

  redis:
    image: redis:7
    ports:
      - "6379:6379" # Redis будет доступен на localhost:6379